"""Supervised LoRA training for the local spreadsheet agent using Tinker.

Run `build_agent_sft_data.py` first. `--dry-run` validates rendered data and
does not create a Tinker session or submit training work.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

import yaml

RESEARCH_DIR = Path(__file__).resolve().parents[1]
if str(RESEARCH_DIR) not in sys.path:
    sys.path.insert(0, str(RESEARCH_DIR))

from baseline.common import load_env


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--data", required=True, help="JSONL generated by build_agent_sft_data.py")
    p.add_argument("--validation-data", help="Optional held-out JSONL for loss monitoring")
    p.add_argument("--config", default="config/qwen_lora.yaml")
    p.add_argument("--out-dir", required=True)
    p.add_argument("--epochs", type=int)
    p.add_argument("--batch-size", type=int)
    p.add_argument("--learning-rate", type=float)
    p.add_argument("--rank", type=int)
    p.add_argument("--dry-run", action="store_true")
    return p.parse_args()


def load_config(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        config = yaml.safe_load(f) or {}
    if not isinstance(config, dict):
        raise ValueError("LoRA config must be a YAML mapping")
    return config


def read_examples(path: Path) -> list[dict]:
    rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    for row in rows:
        messages = row.get("messages")
        if not isinstance(messages, list) or not messages or messages[-1].get("role") != "assistant":
            raise ValueError(f"invalid SFT example in {path}: final message must be an assistant target")
    return rows


def datum_examples(rows: list[dict], renderer, *, max_length: int):
    """Delay cookbook imports so --dry-run and offline tests need no Tinker install."""
    from tinker_cookbook.supervised.data import conversation_to_datum
    from tinker_cookbook.renderers import TrainOnWhat

    return [
        conversation_to_datum(
            row["messages"], renderer, max_length=max_length,
            train_on_what=TrainOnWhat.LAST_ASSISTANT_MESSAGE,
        )
        for row in rows
    ]


def batches(rows: list, size: int):
    for start in range(0, len(rows), size):
        yield rows[start:start + size]


def mean_loss(results: list) -> float | None:
    values = [float(result.loss) for result in results if getattr(result, "loss", None) is not None]
    return sum(values) / len(values) if values else None


def main() -> None:
    args = parse_args()
    load_env()
    config = load_config(Path(args.config))
    base_model = config["base_model"]
    renderer_name = config["renderer"]
    epochs = args.epochs if args.epochs is not None else int(config.get("epochs", 2))
    batch_size = args.batch_size if args.batch_size is not None else int(config.get("batch_size", 4))
    learning_rate = args.learning_rate if args.learning_rate is not None else float(config.get("learning_rate", 1e-4))
    rank = args.rank if args.rank is not None else int(config.get("rank", 16))
    max_length = int(config.get("max_length", 32768))
    seed = int(config.get("seed", 20260905))
    train_rows = read_examples(Path(args.data))
    validation_rows = read_examples(Path(args.validation_data)) if args.validation_data else []
    summary = {"base_model": base_model, "renderer": renderer_name, "rank": rank, "epochs": epochs,
               "batch_size": batch_size, "learning_rate": learning_rate, "max_length": max_length,
               "train_examples": len(train_rows), "validation_examples": len(validation_rows), "dry_run": args.dry_run}
    if not train_rows:
        raise ValueError("training data contains no examples")
    if args.dry_run:
        print(json.dumps(summary, indent=2))
        return

    import tinker
    from tinker import types
    from tinker_cookbook import renderers
    from tinker_cookbook.tokenizer_utils import get_tokenizer

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    random.Random(seed).shuffle(train_rows)
    renderer = renderers.get_renderer(renderer_name, get_tokenizer(base_model))
    train_data = datum_examples(train_rows, renderer, max_length=max_length)
    validation_data = datum_examples(validation_rows, renderer, max_length=max_length) if validation_rows else []
    service = tinker.ServiceClient(project_id=config.get("project_id"))
    trainer = service.create_lora_training_client(base_model=base_model, rank=rank, seed=seed)
    history = []
    step = 0
    for epoch in range(1, epochs + 1):
        random.Random(seed + epoch).shuffle(train_data)
        train_results = []
        for batch in batches(train_data, batch_size):
            forward = trainer.forward_backward(batch, "cross_entropy")
            update = trainer.optim_step(types.AdamParams(learning_rate=learning_rate))
            train_results.append(forward.result())
            update.result()
            step += 1
        validation_loss = None
        if validation_data:
            validation_loss = mean_loss([trainer.forward(batch, "cross_entropy").result() for batch in batches(validation_data, batch_size)])
        checkpoint = trainer.save_weights_for_sampler(f"spreadsheet-agent-epoch-{epoch}").result().path
        state = trainer.save_state(f"spreadsheet-agent-step-{step}").result().path
        row = {"epoch": epoch, "step": step, "train_loss": mean_loss(train_results), "validation_loss": validation_loss,
               "sampler_path": checkpoint, "state_path": state}
        history.append(row)
        (out_dir / "training_state.json").write_text(json.dumps({**summary, "history": history}, indent=2) + "\n", encoding="utf-8")
        print(json.dumps(row), flush=True)


if __name__ == "__main__":
    main()
